[versions]
accompanist = "0.31.6-rc"
activity-compose = "1.8.1"
agp = "8.1.4"
appcompat = "1.6.1"
compose-bom = "2023.10.01"
compose-lottie = "5.2.0"
compose-navigation = "2.7.5"
constraintlayout = "2.1.4"
constraintlayout-compose = "1.0.1"
coil = "2.4.0"
core-ktx = "1.12.0"
core-splashscreen = "1.0.1"
core-testing = "2.2.0"
dagger = "2.48"
datastore = "1.0.0"
detekt = "1.23.3"
espresso-core = "3.5.1"
hilt = "1.1.0"
junit = "4.13.2"
junit-android-runner = "1.1.5"
ktlint-wrapper-plugin = "11.6.1"
kotlin = "1.9.10"
kotlinx-coroutines = "1.7.3"
kotlinx-serialization-json = "1.6.0"
kotest = "5.6.2"
ksp = "1.9.10-1.0.13"
ktlint_compose_rules = "0.3.3"
lifecycle = "2.7.0-rc01"
material-icons = "1.5.4"
media3-exoplayer = "1.2.0"
mockk = "1.13.5"
okhttp = "4.11.0"
paging = "3.2.1"
play-publishing = "3.8.4"
retrofit = "2.9.0"
roboelectric = "4.10.3"
room = "2.6.0"
security-app-authenticator = "1.0.0-alpha02"
security-crypto = "1.1.0-alpha06"
security-identity-credential = "1.0.0-alpha03"
secp256k1-kmp = "0.11.0"
spongycastle = "1.58.0.0"
spotless = "6.22.0"
sqlcipher-android = "4.5.3"
telephoto = "0.7.1"
timber = "5.0.1"
url-detector = "0.1.23"

[libraries]
# Core libs
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version = "lifecycle" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons" }

# UI libs
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-animation = { group = "androidx.compose.animation", name = "animation" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
compose-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
compose-placeholdermaterial = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
compose-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
compose-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout-compose" }

lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "compose-lottie" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
navigation-hilt = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt" }
navigation-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }

paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
paging-compose = { module = "androidx.paging:paging-compose", version = "paging" }

# DI libs
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt" }
hilt-compiler-dagger = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
hilt-compiler-android = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }

# Networking libs
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
retrofit-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version = "1.0.0" }

url-detector = { module = "io.github.url-detector:url-detector", version.ref = "url-detector" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

# Database libs
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
paging-room = { module = "androidx.room:room-paging", version.ref = "room" }
sqlcipher-android = { module = "net.zetetic:sqlcipher-android", version.ref = "sqlcipher-android" }

# Media libs
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
telephoto-zoomable-image = { module = "me.saket.telephoto:zoomable-image", version.ref = "telephoto" }
telephoto-zoomable-image-coil = { module = "me.saket.telephoto:zoomable-image-coil", version.ref = "telephoto" }
media3-exoplayer-core = { module = "androidx.media3:media3-exoplayer", version.ref = "media3-exoplayer" }
media3-exoplayer-ui = { module = "androidx.media3:media3-ui", version.ref = "media3-exoplayer" }

# Other libs
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
ktlint_compose_rules = { module = "io.nlopez.compose.rules:ktlint", version.ref = "ktlint_compose_rules" }

# Data storage libs
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# Crytpo libs
secp256k1-kmp-jvm = { module = "fr.acinq.secp256k1:secp256k1-kmp-jvm", version.ref = "secp256k1-kmp" }
secp256k1-kmp-jni-android = { module = "fr.acinq.secp256k1:secp256k1-kmp-jni-android", version.ref = "secp256k1-kmp" }
secp256k1-kmp-jni-jvm = { module = "fr.acinq.secp256k1:secp256k1-kmp-jni-jvm", version.ref = "secp256k1-kmp" }
spongycastle-core = { module = "com.madgag.spongycastle:core", version.ref = "spongycastle" }

androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "security-crypto" }
androidx-security-app-authenticator = { module = "androidx.security:security-app-authenticator", version.ref = "security-app-authenticator" }
androidx-security-identity-credential = { module = "androidx.security:security-identity-credential", version.ref = "security-identity-credential" }

# Tests libs
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-android-runner = { group = "androidx.test.ext", name = "junit", version.ref = "junit-android-runner" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "roboelectric" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "core-testing" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines"}
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-json = { module = "io.kotest:kotest-assertions-json", version.ref = "kotest" }

[bundles]
hilt = ["hilt-android", "navigation-hilt"]
hilt-compiler = ["hilt-compiler", "hilt-compiler-dagger", "hilt-compiler-android"]

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
play-publishing = { id = "com.github.triplet.play", version.ref = "play-publishing" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless"}
ktlint-wrapper-plugin = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-wrapper-plugin" }